apiVersion: v1
kind: ClusterConfig
metadata:
  name: expense
  region: us-east-1
managedNodeGroups:
  - name:  expense
    instanceType:
    minSize: 1
    maxSize: 1
    spot: true
    desiredCapacity: 3

