apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense  # Specify the namespace here
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat:latest
      ports:
        - containerPort: 8080
