apiVersion: v1
kind: Pod
metadata:
  name: expense
  namespace: expense  # Specify the namespace here
spec:
  containers:
#    - name: nginx
#      image: nginx:latest
#      ports:
#        - containerPort: 80
    - name: centos
      image: centos:latest
  
#  ➜  learn-kubernetes git:(main) kubectl get pods
#  NAME      READY   STATUS             RESTARTS      AGE
#  expense   0/1     CrashLoopBackOff   2 (26s ago)   60s
#  ➜  learn-kubernetes git:(main) kubectl get pods



# kubectl port-forward pod/nginx 80:80 -n expense
# kubectl port-forward pod/tomcat 8080:8080 -n expense &
#fg
