apiVersion: v1
kind: Pod
metadata:
  name: expense
  namespace: expense
spec:
  containers:
    - name: centos
      image: centos:latest
      command: [ "sleep", "3600" ]  # Keeps the container running for 1 hour




# kubectl port-forward pod/nginx 80:80 -n expense
# kubectl port-forward pod/tomcat 8080:8080 -n expense &
#fg
