apiVersion: v1
kind: pod
metadata:
  - name: expense
    labels:
      app: expense
    environment:
      - name: DB_HOST
        value: "your-db-host"
      - name: DB_USER
        value: "root"
      - name: DB_PASSWORD
        value: "ExpenseApp@1"
    annotations:
      description: This pod runs the expense tracking application.
      version: "1.0"
spec:
  containers:
  - name: expense-app
    image: your-docker-image-name:latest
    ports:
    - containerPort: 8080
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
    resources:
    