apiVersion: v1
kind: Pod
metadata:
  name: configmap-referring
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:              # Load all key-value pairs from the ConfigMap as environment variables
        - configMapRef:
            name: configmap # The name of the ConfigMap to reference (metadata.name of the ConfigMap)
            optional: true  # If true, the pod will still start even if the ConfigMap is missing
      env:                  # Defines individual environment variables for the container
        - name: name
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: name
        - name: age
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: age