apiVersion : v1
kind: Pod
metadata:
  name: configmap-referring
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: configmap
            optional: true
#      env:
#        - name: name
#          valueFrom:
#            configMapKeyRef:
#              name: configmap
#              key: name
#        - name: age
#          valueFrom:
#            configMapKeyRef:
#              name: configmap
#              key: age