apiVersion: v1
kind: Pod
metadata:
  name: secret-mapping
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:
        - secretRef:
            name: secret
            optional: true
