apiVersion: v1
kind: Pod
metadata:
  name: expense
  namespace: expense
  labels:
    app: web-application
  annotations:
    prasad/url: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: NGINX_CONFIG_PATH
          value: "/usr/share/nginx/nginx.service"
