apiVersion: v1
kind: ConfigMap
metadata:
  name: env-demo
  namespace: expense
  labels:
    name: env
data:
  name: hari
  age: "25"
  class: "16"
  course: devops

---
apiVersion: v1
kind: Secret                          # Fixed case from 'secret' to 'Secret'
metadata:
  name: secret-demo
  namespace: expense
  labels:
    name: secret
type: Opaque
data:
  username: "admin"
  password: "password123"

#  username: "YWRtaW4="                   # Base64 encoded value of 'admin'
#  password: "cGFzc3dvcmQxMjM="           # Base64 encoded value of 'password123'

---
apiVersion: v1
kind: Pod
metadata:
  name: env
  namespace: expense
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: env-demo
        - secretRef:
            name: secret-demo
