apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    env: dev
    project: expense
type: Opaque
data:
  name: aGFyaQ==  # "hari" in Base64
  age: MjU=       # "25" in Base64

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
  envFrom:
    - secretRef:  # Changed from configMapRef to secretRef
      name: secret
      optional: true
