apiVersion: v1
kind: Pod
metadata:
  name: secret-mapping
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:            # Load all key-value pairs from the ConfigMap as environment variables
        - secretRef:
            name: secret
            optional: true
#      env:                 # Defines individual environment variables for the container
#        - name: USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: secret                  # Name of the Secret
#              key: username                 # The key within the Secret
#              optional: true                # If true, the Pod will start even if the key is missing
#        - name: PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: secret                  # Name of the Secret
#              key: password                 # The key within the Secret
#              optional: true                # If true, the Pod will start even if the key is missing
#################################################################

####### kubectl get secrets