apiVersion: v1
metadata:
  name: load-balancer
  namespace: expense
  labels:
    app: load-balancer
kind: Service
spec:
  selector:
    app: load-balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080